* Changelog/Notes
** 220427 -- Started transferring initial chapter on quantum information (PDK)

*Morning*

Translating Dirk's ch. 7 about quantum information.  Emphasis on photonic implementation as this will be the focus of the course.

I am currently at the section on two-qubit gates.

*Afternoon*

I have Ch. 7 as it is translated.  There are several things that still need to be fleshed out.

Some questions items I would like to address:

 1. [ ] We need a logo for the book!
 2. There are some images that aren't showing up in my mathematica notebooks... however, in general it seems we will likely need to be a bit more graphical/illustrative in our approach for the UG lab.
    + [ ] I need images that are missing for me now if possible.
 3. [ ] We should probably be a bit more exposatory on motivation for math throughout:
    + For instance -- instead of listing out the gates one by one with their math equivalents and how they are formulated, there should also be a description at the top as to why each gate is important.
    + What function does it have in general, and why are we taking the time to introduce it?
    + We should also add more schematics with the diagrammatic form of each gate, as well as some realistic examples of optical implementations at the least
 4. [ ] We now need to tie-in with the equipment that we have more I think.
    + *Appraoch 1* Should we stick with purely optical implementation examples?
    + *Approach 2* Or, should we be more general, but systematically show an example in each kind of platform?  /I vote for this option/.  
      + Example: For each gate we would systematically list out each example platform from a pre-defined list, and then note examples of how each gate is implemented in that respective platform (or at least an example).
      + It would be good to also note current limitations and areas where researchers/engineers are trying to improve upon conventional approaches (for instance integrated-photonics implementations of free-space optical gates)...


* Tasks
** DONE Complete translating Ch. 7 on quantum information
CLOSED: [2022-04-27 Wed 13:24]
** DONE Notes on action items and thoughts of directions for discussion
CLOSED: [2022-04-27 Wed 13:24]
** TODO Start adding in additional explanatory material and bringing to proper level for undergrad course.  
